### ISSUE TITLE
openjij.GPUChimeraSASampler does not work

### ISSUE THREAD

**Issue by j-i-k-o** [OpenJij/OpenJij#129]
Following python code raises the error (shape mismatching in NumPy)

```python
a = oj.GPUChimeraSASampler(unit_num_L = 2)
a.sample_ising(h={0: 0.1, 1: 0.4}, J={(2,5): 0.3})
```
error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/ssd/workspace/linux/workspace/Jij/openjij/OpenJij/openjij/sampler/chimera_gpu/gpu_sa_sampler.py", line 113, in sample_ising
    return self._sampling(model, beta_min, beta_max,
  File "/mnt/ssd/workspace/linux/workspace/Jij/openjij/OpenJij/openjij/sampler/sa_sampler.py", line 204, in _sampling
    response = self._cxxjij_sampling(
  File "/mnt/ssd/workspace/linux/workspace/Jij/openjij/OpenJij/openjij/sampler/sampler.py", line 120, in _cxxjij_sampling
    sampling_time = exec_sampling()
  File "/mnt/ssd/workspace/linux/workspace/Jij/openjij/OpenJij/openjij/sampler/sampler.py", line 27, in wrapper
    func(*args, **kargs)
  File "/mnt/ssd/workspace/linux/workspace/Jij/openjij/OpenJij/openjij/sampler/sampler.py", line 113, in exec_sampling
    energies.append(model.calc_energy(result_state))
  File "/mnt/ssd/workspace/linux/workspace/Jij/openjij/OpenJij/openjij/model/model.py", line 150, in calc_energy
    energy = (np.dot(_state, np.dot(int_mat, _state)) -
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (4,4) and (32,) not aligned: 4 (dim 1) != 32 (dim 0)
```

This error may occur since the Chimera graph with 2 * 2 * 8 spins is interpreted to Binary Quadratic Model with four spins when evaluating `calc_energy` inside Python implementation of OpenJij.

**Comment by j-i-k-o** [comment]
This issue is solved in #132.
