### ISSUE TITLE
ContinuousTimeQuantumIsing solver failed under gcc 10

### ISSUE THREAD

**Issue by j-i-k-o** [OpenJij/OpenJij#144]
# Summary
`python setup.py test` command fails under the latest version of  gcc.

# Versions
gcc-libs ((before)9.3.0-1 -> (after)10.1.0-2)
gcc ((before)9.3.0-1 -> (after)10.1.0-2)
gcc-fortran ((before)9.3.0-1 -> (after)10.1.0-2)

# Outputs

```sh
test_benchmark (tests.test_utils.TestUtils) ... ok
test_str_key_success_prob (tests.test_utils.TestUtils) ... ok
test_var_type (tests.test_utils.TestUtils) ... ok
test_csqa (tests.test_sampler.TestSamplers) ... FAIL
test_sa (tests.test_sampler.TestSamplers) ... ok
test_sqa (tests.test_sampler.TestSamplers) ... ok
test_bqm (tests.test_model.ModelTest) ... ok
test_bqm_calc_energy (tests.test_model.ModelTest) ... ok
test_bqm_constructor (tests.test_model.ModelTest) ... ok
test_chimera (tests.test_model.ModelTest) ... ok
test_chimera_converter (tests.test_model.ModelTest) ... ok
test_energy_consistency (tests.test_model.ModelTest) ... ok
test_get_chimera_graph (tests.test_model.ModelTest) ... ok
test_interaction_matrix (tests.test_model.ModelTest) ... ok
test_ising_dict (tests.test_model.ModelTest) ... ok
test_king_graph (tests.test_model.ModelTest) ... ok
test_transfer_to_cxxjij (tests.test_model.ModelTest) ... ok
test_variable_type (tests.test_model.VariableTypeTest) ... ok
test_ContinuousTimeSwendsenWang_ContinuousTimeIsing_Sparse (tests.test.CXXTest) ... FAIL
test_SingleSpinFlip_ClassicalIsing_Dense (tests.test.CXXTest) ... ok
test_SingleSpinFlip_ClassicalIsing_Sparse (tests.test.CXXTest) ... ok
test_SingleSpinFlip_TransverseIsing_Dense (tests.test.CXXTest) ... ok
test_SingleSpinFlip_TransverseIsing_Sparse (tests.test.CXXTest) ... ok
test_SwendsenWang_ClassicalIsing_Sparse (tests.test.CXXTest) ... ok
test_hubo_sampling (tests.test_hubo.HUBOTest) ... ok

======================================================================
FAIL: test_csqa (tests.test_sampler.TestSamplers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jiko/workspace/Jij/openjij/OpenJij/tests/test_sampler.py", line 120, in test_csqa
    self.samplers(sampler,
  File "/home/jiko/workspace/Jij/openjij/OpenJij/tests/test_sampler.py", line 48, in samplers
    self._test_response(res, self.e_q, self.ground_q)
  File "/home/jiko/workspace/Jij/openjij/OpenJij/tests/test_sampler.py", line 53, in _test_response
    self.assertListEqual(s_g, list(res.states[0]))
AssertionError: Lists differ: [1, 1, 0, 0, 0] != [1, 1, 0, 0, 1]

First differing element 4:
0
1

- [1, 1, 0, 0, 0]
?              ^

+ [1, 1, 0, 0, 1]
?              ^


======================================================================
FAIL: test_ContinuousTimeSwendsenWang_ContinuousTimeIsing_Sparse (tests.test.CXXTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jiko/workspace/Jij/openjij/OpenJij/tests/test.py", line 291, in test_ContinuousTimeSwendsenWang_ContinuousTimeIsing_Sparse
    self.assertTrue(self.true_groundstate == result_spin)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 25 tests in 4.749s

```

**Comment by j-i-k-o** [comment]
It seems that the modification of `std::hash` in gcc10 affects the generated time series by MCMC, which is not a bug.
