### ISSUE TITLE
Error in CSQASampler()

### ISSUE THREAD

**Issue by j-i-k-o** [OpenJij/OpenJij#217]
**Describe the bug**
`CSQASampler()` causes the NoneType-related error.

**To Reproduce**
```python
>>> import openjij as oj
>>> h = {0: -1, 1: -1, 2: 1, 3: 1}
>>> J = {(0, 1): -1, (3, 4): -1}
>>> sampler = oj.CSQASampler()
>>> res = sampler.sample_ising(h, J)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/openjij/sampler/csqa_sampler.py", line 103, in sample_ising
    self._annealing_schedule_setting(
  File "/usr/local/lib/python3.9/site-packages/openjij/sampler/sqa_sampler.py", line 228, in _annealing_schedule_setting
    self._schedule, beta_gamma = quartic_ising_schedule(
  File "/usr/local/lib/python3.9/site-packages/openjij/sampler/sqa_sampler.py", line 270, in quartic_ising_schedule
    s = np.linspace(0, 1, num_sweeps)
  File "<__array_function__ internals>", line 5, in linspace
  File "/usr/local/lib/python3.9/site-packages/numpy/core/function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Expected behavior**
* No error outputs

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Version: Python 3.9.6

**Additional context**

**Comment by durga0201** [comment]
Showing attribute error @j-i-k-o 
```
>>> import openjij as oj
>>> h = {0: -1, 1: -1, 2: 1, 3: 1}
>>> J = {(0, 1): -1, (3, 4): -1}
>>> sampler = oj.CSQASampler()
>>> res = sampler.sample_ising(h, J)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rag9704/miniforge3/envs/ox/lib/python3.11/site-packages/openjij/sampler/csqa_sampler.py", line 148, in sample_ising
    init_generator(), ising_graph, self.gamma
                                   ^^^^^^^^^^
AttributeError: 'CSQASampler' object has no attribute 'gamma'
```

**Comment by durga0201** [comment]
```
>>> import openjij as oj
>>> J = {(0, 1): -1, (3, 4): -1}
>>> h = {0: -1, 1: -1, 2: 1, 3: 1}
>>> sampler = oj.CSQASampler()
>>> res = sampler.sample_ising(h, J)
>>> res
Response(rec.array([([ 1,  1, -1, -1, -1], -6., 1)],
          dtype=[('sample', 'i1', (5,)), ('energy', '<f8'), ('num_occurrences', '<i8')]), Variables([0, 1, 2, 3, 4]), {'system': [{'spin_config': [[(2.6032104587605174, -1)], [(3.6352152132798925, -1)], [(2.5404473200985085, 1)], [(0.1657088948410277, 1)], [(1.837028070825064, 1)], [(2.3262034605975996, -1)]]}], 'sampling_time': 8590.750047005713, 'execution_time': 8463.833946734667, 'list_exec_times': array([8463.83394673]), 'schedule': {'beta': 5.0, 'gamma': 1.0, 'num_sweeps': 1000}}, 'SPIN')
```
Was able to resolve it @j-i-k-o

**Comment by durga0201** [comment]
@j-i-k-o this should be closed as well.
